apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "activity-db"
spec:
  configuration:
    clusters:
      - name: "cluster1"
        layout:
          shardsCount: 1
          replicasCount: 1
